Simplify script, only attempt replace if necessary

diff --git a/solr/docker/scripts/init-var-solr b/solr/docker/scripts/init-var-solr
--- a/solr/docker/scripts/init-var-solr
+++ b/solr/docker/scripts/init-var-solr
@@ -57,10 +57,8 @@ if [ ! -d "$DIR/logs" ]; then
 fi
 
 if [ ! -f "$DIR/log4j2.xml" ]; then
-    #echo "Copying log4j2.xml"
     cp -a /opt/solr/server/resources/log4j2.xml "$DIR/log4j2.xml"
-else
-    # Making sure sysprop name is upgraded from solr.log.dir to solr.logs.dir
-    sed -i 's/solr\.log\.dir/solr.logs.dir/g' "$DIR/log4j2.xml"
+elif grep -q 'solr\.log\.dir' "$DIR/log4j2.xml"; then
+    [ -w "$DIR/log4j2.xml" ] && sed -i 's/solr\.log\.dir/solr.logs.dir/g' "$DIR/log4j2.xml" 2>/dev/null || echo "Warning: Could not migrate solr.log.dir to solr.logs.dir in $DIR/log4j2.xml" >&2
 fi
 
