SOLR-15281: Add optional SOLR_GC_LOGS_DIR and SOLR_GC_LOG_FILE options for bin/solr

diff --git a/solr/bin/solr b/solr/bin/solr
--- a/solr/bin/solr
+++ b/solr/bin/solr
@@ -1974,6 +1974,14 @@ if [ "${SOLR_HOME:0:${#EXAMPLE_DIR}}" = "$EXAMPLE_DIR" ]; then
   SOLR_LOGS_DIR="$SOLR_HOME/../logs"
 fi
 
+if [ -z "$SOLR_GC_LOGS_DIR" ]; then
+  SOLR_GC_LOGS_DIR="$SOLR_LOGS_DIR"
+fi
+
+if [ -z "$SOLR_GC_LOG_FILE" ]; then
+  SOLR_GC_LOG_FILE="solr_gc.log"
+fi
+
 LOG4J_CONFIG=()
 if [ -n "$LOG4J_PROPS" ]; then
   LOG4J_CONFIG+=("-Dlog4j.configurationFile=$LOG4J_PROPS")
@@ -2004,7 +2012,7 @@ if [ "${SOLR_LOG_PRESTART_ROTATION:=false}" == "true" ]; then
   # Enable any of these if you require old remove/archive behavior
   #run_tool utils -s "$DEFAULT_SERVER_DIR" -l "$SOLR_LOGS_DIR" $q -remove_old_solr_logs 7 || echo "Failed removing old solr logs"
   #run_tool utils -s "$DEFAULT_SERVER_DIR" -l "$SOLR_LOGS_DIR" $q -archive_gc_logs $q     || echo "Failed archiving old GC logs"
-  #run_tool utils -s "$DEFAULT_SERVER_DIR" -l "$SOLR_LOGS_DIR" $q -archive_console_logs   || echo "Failed archiving old console logs"
+  #run_tool utils -s "$DEFAULT_SERVER_DIR" -l "$SOLR_GC_LOGS_DIR" $q -archive_console_logs   || echo "Failed archiving old console logs"
   run_tool utils -s "$DEFAULT_SERVER_DIR" -l "$SOLR_LOGS_DIR" $q -rotate_solr_logs 10    || echo "Failed rotating old solr logs"
 fi
 
@@ -2029,7 +2037,7 @@ if [ "$GC_LOG_OPTS" != "" ]; then
       gc_log_flag="-Xverbosegclog"
     fi
     if [ -z ${JAVA8_GC_LOG_FILE_OPTS+x} ]; then
-      GC_LOG_OPTS+=("$gc_log_flag:$SOLR_LOGS_DIR/solr_gc.log" '-XX:+UseGCLogFileRotation' '-XX:NumberOfGCLogFiles=9' '-XX:GCLogFileSize=20M')
+      GC_LOG_OPTS+=("$gc_log_flag:$SOLR_GC_LOGS_DIR/$SOLR_GC_LOG_FILE" '-XX:+UseGCLogFileRotation' '-XX:NumberOfGCLogFiles=9' '-XX:GCLogFileSize=20M')
     else
       GC_LOG_OPTS+=($JAVA8_GC_LOG_FILE_OPTS)
     fi
@@ -2040,7 +2048,7 @@ if [ "$GC_LOG_OPTS" != "" ]; then
       # for simplicity, we only look at the prefix '-Xlog:gc'
       # (if 'all' or multiple tags are used starting with anything other then 'gc' the user is on their own)
       # if a single additional ':' exists in param, then there is already an explicit output specifier
-      GC_LOG_OPTS[$i]=$(echo ${GC_LOG_OPTS[$i]} | sed "s|^\(-Xlog:gc[^:]*$\)|\1:file=$SOLR_LOGS_DIR/solr_gc.log:time,uptime:filecount=9,filesize=20M|")
+      GC_LOG_OPTS[$i]=$(echo ${GC_LOG_OPTS[$i]} | sed "s|^\(-Xlog:gc[^:]*$\)|\1:file=$SOLR_GC_LOGS_DIR/$SOLR_GC_LOG_FILE:time,uptime:filecount=9,filesize=20M|")
     done
   fi
 fi
@@ -2265,6 +2273,7 @@ function start_solr() {
     "-Dsolr.default.confdir=$DEFAULT_CONFDIR" "${LOG4J_CONFIG[@]}" "${SOLR_OPTS[@]}" "${SECURITY_MANAGER_OPTS[@]}" "${SOLR_ADMIN_UI}")
 
   mk_writable_dir "$SOLR_LOGS_DIR" "Logs"
+  mk_writable_dir "$SOLR_GC_LOGS_DIR" "GC Logs"
   if [[ -n "$SOLR_HEAP_DUMP_DIR" ]]; then
     mk_writable_dir "$SOLR_HEAP_DUMP_DIR" "Heap Dump"
   fi
