migrate to using java code for arg parsing and make AuthTool work like other Tools.

diff --git a/solr/bin/solr b/solr/bin/solr
--- a/solr/bin/solr
+++ b/solr/bin/solr
@@ -526,53 +526,6 @@ function print_usage() {
     echo "             <path>:  The Zookeeper path to create. Leading slash is assumed if not present."
     echo "                        Intermediate nodes are created as needed if not present."
     echo ""
-  elif [ "$CMD" == "auth" ]; then
-    echo ""
-    echo "Usage: solr auth enable [--type basicAuth] --credentials user:pass [--block-unknown <true|false>] [--update-include-file-only <true|false>] [-v]"
-    echo "       solr auth enable [--type basicAuth] --prompt <true|false> [--block-unknown <true|false>] [--update-include-file-only <true|false>] [-v]"
-    echo "       solr auth enable --type kerberos --config \"<kerberos configs>\" [--update-include-file-only <true|false>] [-v]"
-    echo "       solr auth disable [--update-include-file-only <true|false>] [-v]"
-    echo ""
-    echo "  Updates or enables/disables authentication.  Must be run on the machine hosting Solr."
-    echo ""
-    echo "  --type or -t <type>                    The authentication mechanism (basicAuth or kerberos) to enable. Defaults to 'basicAuth'."
-    echo ""
-    echo "  --credentials <user:pass>              The username and password of the initial user. Applicable for basicAuth only."
-    echo "                                          Note: only one of --prompt or --credentials must be provided"
-    echo ""
-    echo "  --config \"<configs>\"                 Configuration parameters (Solr startup parameters). Required and applicable only for Kerberos"
-    echo ""
-    echo "  --solr-include-file <includeFilePath>  Specify the full path to the include file in the environment."
-    echo "                                          If not specified this script looks for an include file named solr.in.sh to set environment variables. "
-    echo "                                          Specifically,the following locations are searched in this order:"
-    echo "                                              <script location>/."
-    echo "                                              $HOME/.solr.in.sh"
-    echo "                                              /usr/share/solr"
-    echo "                                              /usr/local/share/solr"
-    echo "                                              /etc/default"
-    echo "                                              /var/solr"
-    echo "                                              /opt/solr"
-    echo ""
-    echo "  --prompt <true|false>                  Prompts the user to provide the credentials. Applicable for basicAuth only."
-    echo "                                          Note: only one of --prompt or --credentials must be provided"
-    echo ""
-    echo "  --block-unknown <true|false>           When true, this blocks out access to unauthenticated users. When not provided,"
-    echo "                                          this defaults to false (i.e. unauthenticated users can access all endpoints, except the"
-    echo "                                          operations like collection-edit, security-edit, core-admin-edit etc.). Check the reference"
-    echo "                                          guide for Basic Authentication for more details. Applicable for basicAuth only."
-    echo ""
-    echo "  --update-include-file-only <true|false> Only update the solr.in.sh or solr.in.cmd file, and skip actual enabling/disabling"
-    echo "                                          authentication (i.e. don't update security.json)"
-    echo ""
-    echo "  -z or --zk-host <zkHost>               Zookeeper connection string. Unnecessary if ZK_HOST is defined in solr.in.sh."
-    echo ""
-    echo "  -d or --dir <dir>                      Specify the Solr server directory"
-    echo ""
-    echo "  -s or --solr-home <dir>                Specify the Solr home directory. This is where any credentials or authentication"
-    echo "                                          configuration files (e.g. basicAuth.conf) would be placed."
-    echo ""
-    echo "  -v/--verbose                           Enable more verbose output for this script."
-    echo ""
   fi
 } # end print_usage
 
@@ -830,6 +783,41 @@ if [[ "$SCRIPT_CMD" == "package" ]]; then
   exit $?
 fi
 
+# configure authentication
+if [[ "$SCRIPT_CMD" == "auth" ]]; then
+  echo "About to run auht"
+  : "${SOLR_SERVER_DIR:=$DEFAULT_SERVER_DIR}"
+  if [ ! -e "$SOLR_SERVER_DIR" ]; then
+    echo -e "\nSolr server directory $SOLR_SERVER_DIR not found!\n"
+    exit 1
+  fi
+  
+  if [ -z "${SOLR_HOME:-}" ]; then
+    SOLR_HOME="$SOLR_SERVER_DIR/solr"
+  elif [[ $SOLR_HOME != /* ]]; then
+    if [[ -d "$(pwd -P)/$SOLR_HOME" ]]; then
+      SOLR_HOME="$(pwd -P)/$SOLR_HOME"
+    elif [[ -d "$SOLR_SERVER_DIR/$SOLR_HOME" ]]; then
+      SOLR_HOME="$SOLR_SERVER_DIR/$SOLR_HOME"
+      SOLR_PID_DIR="$SOLR_HOME"
+    fi
+  fi
+  
+  if [ -z "${AUTH_PORT:-}" ]; then
+    for ID in $(ps auxww | grep java | grep start\.jar | awk '{print $2}' | sort -r)
+      do
+        port=$(jetty_port "$ID")
+        if [ "$port" != "" ]; then
+          AUTH_PORT=$port
+          break
+        fi
+      done
+  fi  
+  
+  run_tool auth $@ --solr-url "$SOLR_URL_SCHEME://$SOLR_TOOL_HOST:${AUTH_PORT:-8983}" --auth-conf-dir "$SOLR_HOME" "--solr-include-file" "$SOLR_INCLUDE"
+  exit $?
+fi
+
 # Prevent any zk subcommands from going through with out invoking zk command
 if [[ "$SCRIPT_CMD" == "upconfig" || $SCRIPT_CMD == "downconfig" || $SCRIPT_CMD == "cp" || $SCRIPT_CMD == "rm" || $SCRIPT_CMD == "mv" || $SCRIPT_CMD == "ls" || $SCRIPT_CMD == "mkroot" || $SCRIPT_CMD == "linkconfig" || $SCRIPT_CMD == "updateacls" ]]; then
   print_short_zk_usage "You must invoke this subcommand using the zk command.   bin/solr zk $SCRIPT_CMD."
@@ -1012,142 +1000,6 @@ if [[ "$SCRIPT_CMD" == "zk" ]]; then
     ;;
   esac
 
-  exit $?
-fi
-
-if [[ "$SCRIPT_CMD" == "auth" ]]; then
-
-  VERBOSE=""
-
-  declare -a AUTH_PARAMS
-  if [ $# -gt 0 ]; then
-    while true; do
-      case "${1:-}" in
-        enable|disable)
-            AUTH_OP=$1
-            AUTH_PARAMS=("${AUTH_PARAMS[@]}" "$AUTH_OP")
-            shift
-        ;;
-        -z|--zk-host|-zkHost|--zkHost)
-            ZK_HOST="$2"
-            AUTH_PARAMS=("${AUTH_PARAMS[@]}" "-z" "$ZK_HOST")
-            shift 2
-        ;;
-        -t|--type|-type)
-            AUTH_TYPE="$2"
-            AUTH_PARAMS=("${AUTH_PARAMS[@]}" "--type" "$AUTH_TYPE")
-            shift 2
-        ;;
-        --credentials|-credentials)
-            AUTH_CREDENTIALS="$2"
-            AUTH_PARAMS=("${AUTH_PARAMS[@]}" "--credentials" "$AUTH_CREDENTIALS")
-            shift 2
-        ;;
-        --config|-config)
-            AUTH_CONFIG="$(echo "$2"| base64)"
-            AUTH_PARAMS=("${AUTH_PARAMS[@]}" "--config" "$AUTH_CONFIG")
-            shift 2
-        ;;
-        --solr-include-file|-solrIncludeFile)
-            SOLR_INCLUDE="$2"
-            shift 2
-        ;;
-        --prompt|-prompt)
-            AUTH_PARAMS=("${AUTH_PARAMS[@]}" "--prompt" "$2")
-            shift 2
-        ;;
-        --block-unknown|-blockUnknown)
-            AUTH_PARAMS=("${AUTH_PARAMS[@]}" "--block-unknown" "$2")
-            shift 2
-        ;;
-        --update-include-file-only|-updateIncludeFileOnly|--updateIncludeFileOnly)
-            AUTH_PARAMS=("${AUTH_PARAMS[@]}" "--update-include-file-only" "$2")
-            shift 2
-        ;;
-        -v|--verbose|-verbose)
-            VERBOSE="--verbose"
-            shift
-        ;;
-        -d|--dir|-dir)
-            if [[ -z "$2" || "${2:0:1}" == "-" ]]; then
-              print_usage "$SCRIPT_CMD" "Server directory is required when using the $1 option!"
-              exit 1
-            fi
-
-            if [[ "$2" == "." || "$2" == "./" || "$2" == ".." || "$2" == "../" ]]; then
-              SOLR_SERVER_DIR="$(pwd -P)/$2"
-            else
-              # see if the arg value is relative to the tip vs full path
-              if [[ "$2" != /* ]] && [[ -d "$SOLR_TIP/$2" ]]; then
-                SOLR_SERVER_DIR="$SOLR_TIP/$2"
-              else
-                SOLR_SERVER_DIR="$2"
-              fi
-            fi
-            # resolve it to an absolute path
-            SOLR_SERVER_DIR="$(cd "$SOLR_SERVER_DIR" || (echo "SOLR_SERVER_DIR not found" && exit 1); pwd)"
-            shift 2
-        ;;
-        -s|--solr-home|-solr.home)
-            if [[ -z "$2" || "${2:0:1}" == "-" ]]; then
-              print_usage "$SCRIPT_CMD" "Solr home directory is required when using the $1 option!"
-              exit 1
-            fi
-
-            SOLR_HOME="$2"
-            shift 2
-        ;;
-        --help|-h|-help)
-            print_usage "$SCRIPT_CMD"
-            exit 0
-        ;;
-        --)
-            shift
-            break
-        ;;
-        *)
-            shift
-            break
-        ;;
-      esac
-    done
-  fi
-
-  : "${SOLR_SERVER_DIR:=$DEFAULT_SERVER_DIR}"
-  if [ ! -e "$SOLR_SERVER_DIR" ]; then
-    echo -e "\nSolr server directory $SOLR_SERVER_DIR not found!\n"
-    exit 1
-  fi
-
-  if [ -z "${SOLR_HOME:-}" ]; then
-    SOLR_HOME="$SOLR_SERVER_DIR/solr"
-  elif [[ $SOLR_HOME != /* ]]; then
-    if [[ -d "$(pwd -P)/$SOLR_HOME" ]]; then
-      SOLR_HOME="$(pwd -P)/$SOLR_HOME"
-    elif [[ -d "$SOLR_SERVER_DIR/$SOLR_HOME" ]]; then
-      SOLR_HOME="$SOLR_SERVER_DIR/$SOLR_HOME"
-      SOLR_PID_DIR="$SOLR_HOME"
-    fi
-  fi
-
-  if [ -z "$AUTH_OP" ]; then
-    print_usage "$SCRIPT_CMD"
-    exit 0
-  fi
-
-  AUTH_PARAMS=("${AUTH_PARAMS[@]}" "--solr-include-file" "$SOLR_INCLUDE")
-
-  if [ -z "${AUTH_PORT:-}" ]; then
-    for ID in $(ps auxww | grep java | grep start\.jar | awk '{print $2}' | sort -r)
-      do
-        port=$(jetty_port "$ID")
-        if [ "$port" != "" ]; then
-          AUTH_PORT=$port
-          break
-        fi
-      done
-  fi
-  run_tool auth "${AUTH_PARAMS[@]}" --solr-url "$SOLR_URL_SCHEME://$SOLR_TOOL_HOST:${AUTH_PORT:-8983}" --auth-conf-dir "$SOLR_HOME" $VERBOSE
   exit $?
 fi
 
