Fix issues with || Do not quote possibly empty args in the java run statement

diff --git a/solr/bin/solr b/solr/bin/solr
--- a/solr/bin/solr
+++ b/solr/bin/solr
@@ -1516,7 +1516,7 @@ if [[ "$SCRIPT_CMD" == "auth" ]]; then
               fi
             fi
             # resolve it to an absolute path
-            SOLR_SERVER_DIR="$(cd "$SOLR_SERVER_DIR" || echo "SOLR_SERVER_DIR not found" && exit 1; pwd)"
+            SOLR_SERVER_DIR="$(cd "$SOLR_SERVER_DIR" || (echo "SOLR_SERVER_DIR not found" && exit 1); pwd)"
             shift 2
         ;;
         -s|-solr.home)
@@ -1665,7 +1665,7 @@ if [ $# -gt 0 ]; then
               fi
             fi
             # resolve it to an absolute path
-            SOLR_SERVER_DIR="$(cd "$SOLR_SERVER_DIR" || echo "SOLR_SERVER_DIR not found" && exit 1; pwd)"
+            SOLR_SERVER_DIR="$(cd "$SOLR_SERVER_DIR" || (echo "SOLR_SERVER_DIR not found" && exit 1); pwd)"
             shift 2
         ;;
         -s|-solr.home)
@@ -2159,7 +2159,7 @@ function start_solr() {
 
   # define default GC_TUNE
   if [ -z "${GC_TUNE}" ]; then
-    GC_TUNE_ARR=('-XX:+UseG1GC' \
+      GC_TUNE_ARR=('-XX:+UseG1GC' \
         '-XX:+PerfDisableSharedMem' \
         '-XX:+ParallelRefProcEnabled' \
         '-XX:MaxGCPauseMillis=250' \
@@ -2167,6 +2167,7 @@ function start_solr() {
         '-XX:+AlwaysPreTouch' \
         '-XX:+ExplicitGCInvokesConcurrent')
   else
+    # shellcheck disable=SC2128
     GC_TUNE_ARR=($GC_TUNE) # Stuff the string from outside into first value of the array
   fi
 
@@ -2242,7 +2243,7 @@ function start_solr() {
   fi
 
   # need to launch solr from the server dir
-  cd "$SOLR_SERVER_DIR" || echo -e "\nCd to SOLR_SERVER_DIR failed" && exit 1
+  cd "$SOLR_SERVER_DIR" || (echo -e "\nCd to SOLR_SERVER_DIR failed" && exit 1)
 
   if [ ! -e "$SOLR_SERVER_DIR/start.jar" ]; then
     echo -e "\nERROR: start.jar file not found in $SOLR_SERVER_DIR!\nPlease check your -d parameter to set the correct Solr server directory.\n"
@@ -2285,11 +2286,13 @@ function start_solr() {
   esac
 
   if [ "$run_in_foreground" == "true" ]; then
-    exec "$JAVA" "${SOLR_START_OPTS[@]}" "$SOLR_ADDL_ARGS" -jar start.jar "${SOLR_JETTY_CONFIG[@]}" "$SOLR_JETTY_ADDL_CONFIG"
+    # shellcheck disable=SC2086
+    exec "$JAVA" "${SOLR_START_OPTS[@]}" $SOLR_ADDL_ARGS -jar start.jar "${SOLR_JETTY_CONFIG[@]}" $SOLR_JETTY_ADDL_CONFIG
   else
     # run Solr in the background
-    nohup "$JAVA" "${SOLR_START_OPTS[@]}" "$SOLR_ADDL_ARGS" -Dsolr.log.muteconsole \
-        -jar start.jar "${SOLR_JETTY_CONFIG[@]}" "$SOLR_JETTY_ADDL_CONFIG" \
+    # shellcheck disable=SC2086
+    nohup "$JAVA" "${SOLR_START_OPTS[@]}" $SOLR_ADDL_ARGS -Dsolr.log.muteconsole \
+        -jar start.jar "${SOLR_JETTY_CONFIG[@]}" $SOLR_JETTY_ADDL_CONFIG \
 	1>"$SOLR_LOGS_DIR/solr-$SOLR_PORT-console.log" 2>&1 & echo $! > "$SOLR_PID_DIR/solr-$SOLR_PORT.pid"
 
     # check if /proc/sys/kernel/random/entropy_avail exists then check output of cat /proc/sys/kernel/random/entropy_avail to see if less than 300
